<?php
    $matriz_times = array
    (
        array(
        "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/f/f4/Team_Liquidlogo_square.png",
        "https://upload.wikimedia.org/wikipedia/commons/e/ea/FaZeClan_2019.png",
        "https://gamepedia.cursecdn.com/lolesports_gamepedia_en/thumb/b/b3/Empiresquare.png/1200px-Empiresquare.png",
        
        "https://upload.wikimedia.org/wikipedia/en/f/f0/Fnatic_logo.png",
        "https://pro.eslgaming.com/fileadmin/user_upload/prodb/13466/teamlogos/13481/9f043795-4d8e-4abb-a929-918ea10da76f-white-logo-mark.png",
        "https://pro.eslgaming.com/fileadmin/user_upload/prodb/13466/teamlogos/13487/db6c7dda-ca56-4bad-818f-d1b99e45c1d3-45676cdb-5021-44d0-8382-49ab827f979a.png",
        "https://pro.eslgaming.com/fileadmin/user_upload/prodb/13466/teamlogos/13478/d136f3e4-9146-43f1-a8ab-409cdfdce682-rogue-logo.png",
        "https://pro.eslgaming.com/fileadmin/user_upload/prodb/13466/teamlogos/13472/4a501aef-abd8-4eab-b9c7-c127c4e0e8bc-penta-400.png",
        ),
        
    
        array(
        "--",
        "BlackIce",
        "DustLine",
        "SkullRain",
        "RedCrow",
        "VelvetShell",
        "BloodOrchid",
        "WhiteNoise",
        "ParaBellum",
        "Chimera",
        "GrimSky",
        ),
        
        array(
        "--",
        "Black Ice",
        "Dust Line",
        "Skull Rain",
        "Red Crow",
        "Velvet Shell",
        "Blood Orchid",
        "White Noise",
        "Para Bellum",
        "Chimera",
        "Grim Sky",
        ),
     );
?>